// <auto-generated />
using System;
using Gateway.Shared.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gateway.API.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gateway.Shared.Modelos.LogTelemetria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChaveApi")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataRequisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Projeto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<long>("TempoExecucaoMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataRequisicao");

                    b.HasIndex("Rota");

                    b.ToTable("LogsTelemetria");
                });
#pragma warning restore 612, 618
        }
    }
}
